# -*- coding: utf-8 -*-
"""mall customer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T9kG_bsYrjGKMPMQlS8tCFgYkk2HAL_4
"""

import numpy as np
import pandas as pd

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

df =pd.read_csv('/content/Shopping Mall Customer Segmentation Data .csv')

df.head(-5)

df.shape

df.info()

df.isnull().sum()

df.columns

x = df.iloc[:,[3,4]].values
print(x)

from sklearn.cluster import KMeans

list = []
for i in range(1,11):
  kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
  kmeans.fit(x)
  list.append(kmeans.inertia_)

import seaborn as sns

sns.set()
plt.plot(range(1,11),list)
plt.title('CutOFF point Graph')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

kmeans = KMeans(n_clusters=3, init='k-means++', random_state=42)

# return the label
labels = kmeans.fit_predict(x)
print(labels)

plt.figure(figsize=(10,10))
plt.scatter(x[labels==0,0], x[labels==0,1], s=30, c='grey', label ='cluster 1')
plt.scatter(x[labels==1,0], x[labels==1,1], s=30, c='green', label ='cluster 2')
plt.scatter(x[labels==2,0], x[labels==2,1], s=30, c='blue', label ='cluster 3')

# all in x[labels == #,0] 0 repesent the annual income which is first column in x
# all 1 in x[labels == #,1] 1 represent the sprending score which is second column i x

# Ploting Centroids
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1], s=60, c='cyan', label='Centroids')
plt.title('Customer Groups')
plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.show()